# serial_bridge.param.yaml

serial_bridge:
  ros__parameters:

    # Serial port settings
    port_path: "/dev/ttyS0"
    baud_rate: 115200

    # ERP Mini parameters
    max_speed_mps      :  1.68 # m/s
    max_steering_deg   : 17.00 # deg
    steering_offset_deg:  0.00 # deg